require("dotenv").config();const express=require("express"),cors=require("cors"),helmet=require("helmet"),rateLimit=require("express-rate-limit"),Database=require("better-sqlite3"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),path=require("path");const app=express(),db=new Database(path.join(__dirname,"kaamsetu.db"));app.use(helmet({contentSecurityPolicy:false}));app.use(cors());app.use(express.json({limit:"100kb"}));app.use("/api/",rateLimit({windowMs:9e5,max:300}));app.use(express.static(path.join(__dirname,"../public")));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT DEFAULT 'both',is_admin INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS jobs(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,category TEXT NOT NULL,budget INTEGER NOT NULL,details TEXT,owner_id INTEGER NOT NULL,status TEXT DEFAULT 'open',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS proposals(id INTEGER PRIMARY KEY AUTOINCREMENT,job_id INTEGER NOT NULL,worker_id INTEGER NOT NULL,offer INTEGER NOT NULL,message TEXT,status TEXT DEFAULT 'submitted',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,job_id INTEGER NOT NULL,payer_id INTEGER NOT NULL,worker_id INTEGER,amount INTEGER NOT NULL,fee INTEGER NOT NULL,payout INTEGER NOT NULL,status TEXT DEFAULT 'created',provider_ref TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS disputes(id INTEGER PRIMARY KEY AUTOINCREMENT,job_id INTEGER NOT NULL,opened_by INTEGER NOT NULL,reason TEXT NOT NULL,status TEXT DEFAULT 'open',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const secret=process.env.JWT_SECRET||"dev-only-change-me",feePct=Number(process.env.PLATFORM_FEE_PERCENT||10);function auth(req,res,next){try{let t=(req.headers.authorization||"").replace(/^Bearer /,"");if(!t)throw 0;req.user=jwt.verify(t,secret);next()}catch(e){res.status(401).json({error:"Authentication required"})}}function admin(req,res,next){if(!req.user?.is_admin)return res.status(403).json({error:"Admin only"});next()}
app.get("/api/health",(q,r)=>r.json({ok:true,mode:process.env.PAYMENT_MODE||"sandbox"}));
app.post("/api/auth/signup",async(q,r)=>{let{name,email,password,role="both"}=q.body||{};if(!name||!email||!password||password.length<8)return r.status(400).json({error:"Name, email and password (8+ chars) required"});try{let h=await bcrypt.hash(password,12),x=db.prepare("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)").run(name,email,h,role),u=db.prepare("SELECT id,name,email,role,is_admin FROM users WHERE id=?").get(x.lastInsertRowid);r.json({user:u,token:jwt.sign(u,secret,{expiresIn:"7d"})})}catch(e){r.status(409).json({error:"Email already registered"})}});
app.post("/api/auth/login",async(q,r)=>{let{email,password}=q.body||{},u=db.prepare("SELECT * FROM users WHERE email=?").get(email);if(!u||!(await bcrypt.compare(password,u.password_hash)))return r.status(401).json({error:"Invalid credentials"});let user={id:u.id,name:u.name,email:u.email,role:u.role,is_admin:u.is_admin};r.json({user,token:jwt.sign(user,secret,{expiresIn:"7d"})})});
app.get("/api/jobs",(q,r)=>r.json(db.prepare("SELECT j.*,u.name owner FROM jobs j JOIN users u ON u.id=j.owner_id WHERE j.status='open' ORDER BY j.id DESC").all()));
app.post("/api/jobs",auth,(q,r)=>{let{title,category,budget,details=""}=q.body||{};if(!title||!category||!budget)return r.status(400).json({error:"Missing job fields"});let x=db.prepare("INSERT INTO jobs(title,category,budget,details,owner_id) VALUES(?,?,?,?,?)").run(title,category,Number(budget),details,q.user.id);r.json({id:x.lastInsertRowid})});
app.post("/api/jobs/:id/proposals",auth,(q,r)=>{let j=db.prepare("SELECT * FROM jobs WHERE id=?").get(q.params.id),{offer,message=""}=q.body||{};if(!j)return r.status(404).json({error:"Job not found"});if(j.owner_id===q.user.id)return r.status(400).json({error:"Cannot apply to own job"});let x=db.prepare("INSERT INTO proposals(job_id,worker_id,offer,message) VALUES(?,?,?,?)").run(j.id,q.user.id,Number(offer),message);r.json({id:x.lastInsertRowid})});
app.post("/api/proposals/:id/accept",auth,(q,r)=>{let p=db.prepare("SELECT p.*,j.owner_id FROM proposals p JOIN jobs j ON j.id=p.job_id WHERE p.id=?").get(q.params.id);if(!p||p.owner_id!==q.user.id)return r.status(403).json({error:"Not allowed"});db.prepare("UPDATE proposals SET status='accepted' WHERE id=?").run(p.id);db.prepare("UPDATE proposals SET status='rejected' WHERE job_id=? AND id<>? AND status='submitted'").run(p.job_id,p.id);db.prepare("UPDATE jobs SET status='funded' WHERE id=?").run(p.job_id);r.json({message:"Proposal accepted; create payment next."})});
app.post("/api/jobs/:id/payment/create",auth,(q,r)=>{let j=db.prepare("SELECT * FROM jobs WHERE id=?").get(q.params.id),p=db.prepare("SELECT * FROM proposals WHERE job_id=? AND status='accepted'").get(q.params.id);if(!j||j.owner_id!==q.user.id||!p)return r.status(403).json({error:"Payment not ready"});let amount=Number(p.offer),fee=Math.round(amount*feePct/100),payout=amount-fee,x=db.prepare("INSERT INTO transactions(job_id,payer_id,worker_id,amount,fee,payout) VALUES(?,?,?,?,?,?)").run(j.id,q.user.id,p.worker_id,amount,fee,payout);r.json({transaction_id:x.lastInsertRowid,amount,fee,payout,mode:process.env.PAYMENT_MODE||"sandbox"})});
app.post("/api/jobs/:id/disputes",auth,(q,r)=>{let{reason}=q.body||{};if(!reason)return r.status(400).json({error:"Reason required"});let x=db.prepare("INSERT INTO disputes(job_id,opened_by,reason) VALUES(?,?,?)").run(q.params.id,q.user.id,reason);r.json({id:x.lastInsertRowid,status:"open"})});
app.get("/api/admin/summary",auth,admin,(q,r)=>r.json({users:db.prepare("SELECT COUNT(*) n FROM users").get().n,jobs:db.prepare("SELECT COUNT(*) n FROM jobs").get().n,proposals:db.prepare("SELECT COUNT(*) n FROM proposals").get().n,transactions:db.prepare("SELECT COUNT(*) n FROM transactions").get().n,disputes:db.prepare("SELECT COUNT(*) n FROM disputes WHERE status='open'").get().n}));
app.get("*",(q,r)=>r.sendFile(path.join(__dirname,"../public/index.html")));app.listen(process.env.PORT||3000,()=>console.log("KaamSetu running"));
const PORT = process.env.PORT || 10000;

app.listen(PORT, '0.0.0.0', () => {
  console.log(`Server running on port ${PORT}`);
});
app.get("*",(q,r)=>r.sendFile(path.join(__dirname,"../public/index.html")));app.listen(process.env.PORT||3000,()=>console.log("KaamSetu running"));
const PORT = process.env.PORT || 10000;

app.listen(PORT, '0.0.0.0', () => {
  console.log(`Server running on port ${PORT}`);
});
